# It contains all the configs required in the project
artifacts:
  ARTIFACTS_DIR: artifacts
  prepared_data: prepared
  train_data: train.csv
  test_data: test.csv


source_data: https://raw.githubusercontent.com/atifalimd/dataset/main/data.csv


source_download_dir:
  data_dir: data
  data_file: data.csv
